### ISSUE TITLE
networkName not updated on network change

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-network.js#15]
`networkId` is updated on network change but doesn't appear to update `networkName` when using injectedWeb3 (MetaMask on Brave and Chrome) when logged out.

Issue seen in GSN Starter Kit when switching networks.
https://github.com/OpenZeppelin/starter-kit-gsn

<img width="737" alt="NetworkName" src="https://user-images.githubusercontent.com/28278242/65761629-853e2d80-e162-11e9-894d-f5f29069a99d.png">

**Comment by frangio** [comment]
@ylv-io It seems that event though `networkName` _is_ updated, there is no event emitted to log this change.

https://github.com/OpenZeppelin/openzeppelin-network.js/blob/11866091daa0439581044778b5604c7837ebb6da/src/context/Web3Context.ts#L94-L100

I'm assuming perhaps this was because the event is the same as when `networkId` changes. Can you confirm this? If so, we should perhaps swap the order so that once the `networkId` change event is emitted, `networkName` has been changed as well.

**Comment by abcoathup** [comment]
I am seeing the current network ID and the previous network Name being displayed.

**Comment by ylv-io** [comment]
Hey @abcoathup. Thanks for digging this up. @frangio is absolutely right. It is a one line fix.

**Comment by ylv-io** [comment]
Fixed at https://github.com/OpenZeppelin/openzeppelin-network.js/commit/1944291b76c76bdc2e89378d8cdefac2815d4d20.

**Comment by abcoathup** [comment]
Manually tested with new version and now works as expected.  Thanks @ylv-io.
